### ISSUE TITLE
Create base ActiveRecord class

### ISSUE THREAD

**Issue by johnluxor** [naffiq/yii2-bridge#15]
Create base ActiveRecord class to extend user's models from it. And add there base behaviors etc

**Comment by naffiq** [comment]
What kind of behaviors do we need? I think it's better to generate them with gii to let developers control the way everything works, I'll add more behaviors there.

**Comment by naffiq** [comment]
Generators should cover this problem. In case you still need base ActiveRecord class, describe desired functionality or provide examples
