### ISSUE TITLE
field relativeDropDown add ajax

### ISSUE THREAD

**Issue by johnluxor** [naffiq/yii2-bridge#17]
add ajax loading for select2

**Comment by naffiq** [comment]
The plan is to enable user an option to change behavior of `index` method of generated controllers in Gii. So if `\Yii::$app->request->isAjax`, the data will be returned, as if it was passed to `relativeDropDown` widget.

This data transformation will be used in both `relativeDropDown` and altered `index` widget, so moving this code to external helper is considered, but not mandatory.

**Comment by naffiq** [comment]
Here is short todo list:

- [ ] Move code responsible for data transformation from `relativeDropDown` to external helper
- [ ] Update CRUD Generator for `ajax` requests and use moved code
- [ ] Investigate the way to pass `ajax` url/route to select2 widget and document it

**Comment by naffiq** [comment]
After implementing this functionality on couple of projects, I don't think that this should be generated but written by developers themselves. Select2 by kartik-v allows you to implement it easily. 

Will add instructions to gitbook
