### ISSUE TITLE
SEO and social tags behavior

### ISSUE THREAD

**Issue by naffiq** [naffiq/yii2-bridge#9]
Add behavior for meta tags

**Comment by naffiq** [comment]
I find it a good idea to provide translatable meta tags for different languages, since `v0.8.0` handles translations.

Little todo:

- [ ] Gather list of tags that are required
- [ ] Make a migration and model with fields for those tags and `i18n`
- [ ] Make a behavior and add it to generated models if developer didn't choose otherwise in Gii
- [ ] Create a widget and generate it in `_form`, if model has corresponding behavior

**Comment by altynbek07** [comment]
Будет 4 таблицы.
![default](https://user-images.githubusercontent.com/20629188/39358182-1f1c4bb8-4a37-11e8-8464-8de6c19b26fe.jpg)

**Comment by altynbek07** [comment]
@naffiq Какие еще атрибуты нужны для таблицы **meta_tag_translations**?
